//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalSILweb.WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria_Servicio
    {
        public Categoria_Servicio()
        {
            this.Servicio = new HashSet<Servicio>();
        }
    
        public int IdCategoriaServicio { get; set; }
        public string NombreCategoriaServicio { get; set; }
        public string DescCategoriaServicio { get; set; }
    
        public virtual ICollection<Servicio> Servicio { get; set; }
    }
}
