//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalSILweb.WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaMovoliario
    {
        public CategoriaMovoliario()
        {
            this.Moviliario = new HashSet<Moviliario>();
        }
    
        public int IdCategoriaMoviliario { get; set; }
        public string NomCatMoviliario { get; set; }
        public string DescCategoriaMoviliario { get; set; }
    
        public virtual ICollection<Moviliario> Moviliario { get; set; }
    }
}
