//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalSILweb.WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckIn
    {
        public CheckIn()
        {
            this.CheckOut = new HashSet<CheckOut>();
            this.DetalleCheckIn = new HashSet<DetalleCheckIn>();
            this.DetalleServicioCheckIn = new HashSet<DetalleServicioCheckIn>();
        }
    
        public int IdCheckIn { get; set; }
        public Nullable<int> IdReserva { get; set; }
        public Nullable<System.DateTime> FechaIngeso { get; set; }
    
        public virtual Reserva Reserva { get; set; }
        public virtual ICollection<CheckOut> CheckOut { get; set; }
        public virtual ICollection<DetalleCheckIn> DetalleCheckIn { get; set; }
        public virtual ICollection<DetalleServicioCheckIn> DetalleServicioCheckIn { get; set; }
    }
}
