//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalSILweb.WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCheckIn
    {
        public DetalleCheckIn()
        {
            this.DetallePersonasCheckIn = new HashSet<DetallePersonasCheckIn>();
        }
    
        public int IdDetalleCheckIn { get; set; }
        public Nullable<int> IdCheckIn { get; set; }
        public Nullable<int> IdHabitacion { get; set; }
    
        public virtual CheckIn CheckIn { get; set; }
        public virtual Habitacion Habitacion { get; set; }
        public virtual ICollection<DetallePersonasCheckIn> DetallePersonasCheckIn { get; set; }
    }
}
