//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalSILweb.WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public Facturas()
        {
            this.Comprobante = new HashSet<Comprobante>();
        }
    
        public int IdFacura { get; set; }
        public int IdEmpresa { get; set; }
        public Nullable<decimal> igv { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
    
        public virtual ICollection<Comprobante> Comprobante { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
