//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalSILweb.WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacion
    {
        public Habitacion()
        {
            this.DetalleCheckIn = new HashSet<DetalleCheckIn>();
            this.DetalleMoviliarioHabitacion = new HashSet<DetalleMoviliarioHabitacion>();
            this.DetalleReserva = new HashSet<DetalleReserva>();
        }
    
        public int IdHabitacion { get; set; }
        public string NumeroHabitacion { get; set; }
        public Nullable<int> IdPiso { get; set; }
        public Nullable<int> IdTipoHabitacion { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<DetalleCheckIn> DetalleCheckIn { get; set; }
        public virtual ICollection<DetalleMoviliarioHabitacion> DetalleMoviliarioHabitacion { get; set; }
        public virtual ICollection<DetalleReserva> DetalleReserva { get; set; }
        public virtual Piso Piso { get; set; }
        public virtual TipoHabitacion TipoHabitacion { get; set; }
    }
}
