//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalSILweb.WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.DetallePersonasCheckIn = new HashSet<DetallePersonasCheckIn>();
            this.Reserva = new HashSet<Reserva>();
        }
    
        public string DNI { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public Nullable<System.DateTime> FecNacimiento { get; set; }
        public string Telefono { get; set; }
    
        public virtual ICollection<DetallePersonasCheckIn> DetallePersonasCheckIn { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
