//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalSILweb.WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Piso
    {
        public Piso()
        {
            this.Habitacion = new HashSet<Habitacion>();
        }
    
        public int IdPiso { get; set; }
        public string NombrePiso { get; set; }
    
        public virtual ICollection<Habitacion> Habitacion { get; set; }
    }
}
