//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalSILweb.WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public Servicio()
        {
            this.DetalleServicioCheckIn = new HashSet<DetalleServicioCheckIn>();
        }
    
        public int IdServicio { get; set; }
        public Nullable<int> IdCategoriaServicio { get; set; }
        public string NombreServicio { get; set; }
        public string DescServicio { get; set; }
        public Nullable<decimal> Precio { get; set; }
    
        public virtual Categoria_Servicio Categoria_Servicio { get; set; }
        public virtual ICollection<DetalleServicioCheckIn> DetalleServicioCheckIn { get; set; }
    }
}
