//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalSILweb.WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoHabitacion
    {
        public TipoHabitacion()
        {
            this.Habitacion = new HashSet<Habitacion>();
        }
    
        public int IdTipoHabitacion { get; set; }
        public string NombreTipoHabitacion { get; set; }
        public Nullable<int> NroCamas { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> PrecioCorporativo { get; set; }
    
        public virtual ICollection<Habitacion> Habitacion { get; set; }
    }
}
