//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalSILweb.WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.DetalleUsuarioRol = new HashSet<DetalleUsuarioRol>();
        }
    
        public int IdUsuario { get; set; }
        public string DNIUsuario { get; set; }
        public string NombresUsuario { get; set; }
        public string ApellidosUsuario { get; set; }
        public Nullable<System.DateTime> FecNacimientoUsuario { get; set; }
        public string TelefonoUsuario { get; set; }
        public string CelularUsuario { get; set; }
        public string CorreoUsuario { get; set; }
    
        public virtual ICollection<DetalleUsuarioRol> DetalleUsuarioRol { get; set; }
    }
}
